package com.conveyal.gtfs.flex;

import com.conveyal.r5.streets.Split;
import com.conveyal.r5.transit.TransportNetwork;
import gnu.trove.set.TIntSet;
import gnu.trove.set.hash.TIntHashSet;
import org.locationtech.jts.geom.Polygon;

/// This is an interface for predicates that filter street search states, retaining only those
/// where a particular on-demand service will pick riders up or drop them off. We have separate
/// implementations for polygonal on-demand zones and GTFS "location groups" which are sets of one
/// or more GTFS stops (via "meeting areas").
///
/// This interface unifies stop-based services and polygon services, making stop-based services
/// behave like polygon services with inferred areas.
///
/// Filters are constructed per request through the static factory methods and are not
/// thread-safe because the implementations hold reusable flyweight cursor objects.
public interface OnDemandPlaceFilter {

    /// Returns true when the given vertex is accepted by this filter.
    boolean containsVertex (int vertexIndex);

    /// Returns true when a point off the street network is accepted by this filter.
    /// The point is given in floating-point WGS84 as it has no permanent vertex representation.
    /// This handles arbitrary origin points and analysis destination sample points.
    boolean containsPoint (double lat, double lon, Split split);

    /// Returns a set containing at least all edges whose end states would pass this filter
    /// (from a spatial index), or null when no mechanism exists for such pre-selection and every
    /// state must be examined individually.
    ///
    /// Clipping a large car search result to the interior of comparatively small polygon is
    /// much faster given a set of candidate edges withing the polygon's envelope. On the other
    /// hand, meeting areas are small sets of vertices for which exhaustive scans are cheap.
    TIntSet clipCandidateEdges ();

    /// Returns a filter for the given service's pick-up place.
    static OnDemandPlaceFilter pickUp (OnDemand od, TransportNetwork network) {
        return of(od.fromPolygon, od.fromStopIndexes, network);
    }

    /// Returns a filter for the given service's drop-off place.
    static OnDemandPlaceFilter dropOff (OnDemand od, TransportNetwork network) {
        return of(od.toPolygon, od.toStopIndexes, network);
    }

    /// GTFS load validation ensures every endpoint of every flex trip references exactly one
    /// polygonal zone or location group, but we allow both to be present together in case
    /// on-demand services are generated by non-GTFS mechanisms like scenario modifications.
    /// If neither kind is present, returns a filter containing nothing, making the service unusable.
    private static OnDemandPlaceFilter of (Polygon polygon, int[] stopIndexes, TransportNetwork network) {
        OnDemandPlaceFilter polygonFilter = (polygon == null) ? null
            : new PolygonPlaceFilter(polygon, network.streetLayer);
        OnDemandPlaceFilter areaFilter = (stopIndexes == null) ? null
            : new MeetingAreaPlaceFilter(network.meetingAreas().unionForStops(stopIndexes));
        if (polygonFilter != null && areaFilter != null) {
            return new UnionPlaceFilter(polygonFilter, areaFilter);
        }
        if (polygonFilter != null) return polygonFilter;
        if (areaFilter != null) return areaFilter;
        return new MeetingAreaPlaceFilter(new TIntHashSet());
    }

}
