// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/messages/access_grid.proto

package com.conveyal.r5.analyst.messages;

public final class AccessGridOuterClass {
  private AccessGridOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CellMinuteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.conveyal.r5.analyst.messages.CellMinute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * TODO delta code?
     * </pre>
     */
    java.util.List<java.lang.Integer> getAccessibilityList();
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * TODO delta code?
     * </pre>
     */
    int getAccessibilityCount();
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * TODO delta code?
     * </pre>
     */
    int getAccessibility(int index);
  }
  /**
   * Protobuf type {@code com.conveyal.r5.analyst.messages.CellMinute}
   */
  public static final class CellMinute extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.conveyal.r5.analyst.messages.CellMinute)
      CellMinuteOrBuilder {
    // Use CellMinute.newBuilder() to construct.
    private CellMinute(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CellMinute(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CellMinute defaultInstance;
    public static CellMinute getDefaultInstance() {
      return defaultInstance;
    }

    public CellMinute getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CellMinute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                accessibility_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              accessibility_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                accessibility_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                accessibility_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          accessibility_ = java.util.Collections.unmodifiableList(accessibility_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_CellMinute_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_CellMinute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.class, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder.class);
    }

    public static com.google.protobuf.Parser<CellMinute> PARSER =
        new com.google.protobuf.AbstractParser<CellMinute>() {
      public CellMinute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CellMinute(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CellMinute> getParserForType() {
      return PARSER;
    }

    public static final int ACCESSIBILITY_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> accessibility_;
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * TODO delta code?
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getAccessibilityList() {
      return accessibility_;
    }
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * TODO delta code?
     * </pre>
     */
    public int getAccessibilityCount() {
      return accessibility_.size();
    }
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * TODO delta code?
     * </pre>
     */
    public int getAccessibility(int index) {
      return accessibility_.get(index);
    }

    private void initFields() {
      accessibility_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < accessibility_.size(); i++) {
        output.writeInt32(1, accessibility_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < accessibility_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(accessibility_.get(i));
        }
        size += dataSize;
        size += 1 * getAccessibilityList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.conveyal.r5.analyst.messages.CellMinute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.conveyal.r5.analyst.messages.CellMinute)
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_CellMinute_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_CellMinute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.class, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder.class);
      }

      // Construct using com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accessibility_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_CellMinute_descriptor;
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute getDefaultInstanceForType() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.getDefaultInstance();
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute build() {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute buildPartial() {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute result = new com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          accessibility_ = java.util.Collections.unmodifiableList(accessibility_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.accessibility_ = accessibility_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute) {
          return mergeFrom((com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute other) {
        if (other == com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.getDefaultInstance()) return this;
        if (!other.accessibility_.isEmpty()) {
          if (accessibility_.isEmpty()) {
            accessibility_ = other.accessibility_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAccessibilityIsMutable();
            accessibility_.addAll(other.accessibility_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> accessibility_ = java.util.Collections.emptyList();
      private void ensureAccessibilityIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          accessibility_ = new java.util.ArrayList<java.lang.Integer>(accessibility_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getAccessibilityList() {
        return java.util.Collections.unmodifiableList(accessibility_);
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public int getAccessibilityCount() {
        return accessibility_.size();
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public int getAccessibility(int index) {
        return accessibility_.get(index);
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public Builder setAccessibility(
          int index, int value) {
        ensureAccessibilityIsMutable();
        accessibility_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public Builder addAccessibility(int value) {
        ensureAccessibilityIsMutable();
        accessibility_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public Builder addAllAccessibility(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAccessibilityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accessibility_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * TODO delta code?
       * </pre>
       */
      public Builder clearAccessibility() {
        accessibility_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.conveyal.r5.analyst.messages.CellMinute)
    }

    static {
      defaultInstance = new CellMinute(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.conveyal.r5.analyst.messages.CellMinute)
  }

  public interface CellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.conveyal.r5.analyst.messages.Cell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute> 
        getMinutesList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute getMinutes(int index);
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    int getMinutesCount();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    java.util.List<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder> 
        getMinutesOrBuilderList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder getMinutesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.conveyal.r5.analyst.messages.Cell}
   */
  public static final class Cell extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.conveyal.r5.analyst.messages.Cell)
      CellOrBuilder {
    // Use Cell.newBuilder() to construct.
    private Cell(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cell(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Cell defaultInstance;
    public static Cell getDefaultInstance() {
      return defaultInstance;
    }

    public Cell getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                minutes_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute>();
                mutable_bitField0_ |= 0x00000001;
              }
              minutes_.add(input.readMessage(com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          minutes_ = java.util.Collections.unmodifiableList(minutes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_Cell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_Cell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.class, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder.class);
    }

    public static com.google.protobuf.Parser<Cell> PARSER =
        new com.google.protobuf.AbstractParser<Cell>() {
      public Cell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cell(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Cell> getParserForType() {
      return PARSER;
    }

    public static final int MINUTES_FIELD_NUMBER = 1;
    private java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute> minutes_;
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    public java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute> getMinutesList() {
      return minutes_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    public java.util.List<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder> 
        getMinutesOrBuilderList() {
      return minutes_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    public int getMinutesCount() {
      return minutes_.size();
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute getMinutes(int index) {
      return minutes_.get(index);
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
     */
    public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder getMinutesOrBuilder(
        int index) {
      return minutes_.get(index);
    }

    private void initFields() {
      minutes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < minutes_.size(); i++) {
        output.writeMessage(1, minutes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < minutes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, minutes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.conveyal.r5.analyst.messages.Cell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.conveyal.r5.analyst.messages.Cell)
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_Cell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_Cell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.class, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder.class);
      }

      // Construct using com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMinutesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (minutesBuilder_ == null) {
          minutes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          minutesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_Cell_descriptor;
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell getDefaultInstanceForType() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.getDefaultInstance();
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell build() {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell buildPartial() {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell result = new com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell(this);
        int from_bitField0_ = bitField0_;
        if (minutesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            minutes_ = java.util.Collections.unmodifiableList(minutes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.minutes_ = minutes_;
        } else {
          result.minutes_ = minutesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell) {
          return mergeFrom((com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell other) {
        if (other == com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.getDefaultInstance()) return this;
        if (minutesBuilder_ == null) {
          if (!other.minutes_.isEmpty()) {
            if (minutes_.isEmpty()) {
              minutes_ = other.minutes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMinutesIsMutable();
              minutes_.addAll(other.minutes_);
            }
            onChanged();
          }
        } else {
          if (!other.minutes_.isEmpty()) {
            if (minutesBuilder_.isEmpty()) {
              minutesBuilder_.dispose();
              minutesBuilder_ = null;
              minutes_ = other.minutes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              minutesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMinutesFieldBuilder() : null;
            } else {
              minutesBuilder_.addAllMessages(other.minutes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute> minutes_ =
        java.util.Collections.emptyList();
      private void ensureMinutesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          minutes_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute>(minutes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder> minutesBuilder_;

      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute> getMinutesList() {
        if (minutesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(minutes_);
        } else {
          return minutesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public int getMinutesCount() {
        if (minutesBuilder_ == null) {
          return minutes_.size();
        } else {
          return minutesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute getMinutes(int index) {
        if (minutesBuilder_ == null) {
          return minutes_.get(index);
        } else {
          return minutesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder setMinutes(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute value) {
        if (minutesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinutesIsMutable();
          minutes_.set(index, value);
          onChanged();
        } else {
          minutesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder setMinutes(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder builderForValue) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.set(index, builderForValue.build());
          onChanged();
        } else {
          minutesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder addMinutes(com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute value) {
        if (minutesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinutesIsMutable();
          minutes_.add(value);
          onChanged();
        } else {
          minutesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder addMinutes(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute value) {
        if (minutesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinutesIsMutable();
          minutes_.add(index, value);
          onChanged();
        } else {
          minutesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder addMinutes(
          com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder builderForValue) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.add(builderForValue.build());
          onChanged();
        } else {
          minutesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder addMinutes(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder builderForValue) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.add(index, builderForValue.build());
          onChanged();
        } else {
          minutesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder addAllMinutes(
          java.lang.Iterable<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute> values) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, minutes_);
          onChanged();
        } else {
          minutesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder clearMinutes() {
        if (minutesBuilder_ == null) {
          minutes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          minutesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public Builder removeMinutes(int index) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.remove(index);
          onChanged();
        } else {
          minutesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder getMinutesBuilder(
          int index) {
        return getMinutesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder getMinutesOrBuilder(
          int index) {
        if (minutesBuilder_ == null) {
          return minutes_.get(index);  } else {
          return minutesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public java.util.List<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder> 
           getMinutesOrBuilderList() {
        if (minutesBuilder_ != null) {
          return minutesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(minutes_);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder addMinutesBuilder() {
        return getMinutesFieldBuilder().addBuilder(
            com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder addMinutesBuilder(
          int index) {
        return getMinutesFieldBuilder().addBuilder(
            index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.CellMinute minutes = 1;</code>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder> 
           getMinutesBuilderList() {
        return getMinutesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder> 
          getMinutesFieldBuilder() {
        if (minutesBuilder_ == null) {
          minutesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinute.Builder, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellMinuteOrBuilder>(
                  minutes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          minutes_ = null;
        }
        return minutesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.conveyal.r5.analyst.messages.Cell)
    }

    static {
      defaultInstance = new Cell(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.conveyal.r5.analyst.messages.Cell)
  }

  public interface AccessGridOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.conveyal.r5.analyst.messages.AccessGrid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 width = 1;</code>
     *
     * <pre>
     * width of the grid
     * </pre>
     */
    boolean hasWidth();
    /**
     * <code>required int32 width = 1;</code>
     *
     * <pre>
     * width of the grid
     * </pre>
     */
    int getWidth();

    /**
     * <code>required int32 height = 2;</code>
     *
     * <pre>
     * height of the grid
     * </pre>
     */
    boolean hasHeight();
    /**
     * <code>required int32 height = 2;</code>
     *
     * <pre>
     * height of the grid
     * </pre>
     */
    int getHeight();

    /**
     * <code>required int32 north = 3;</code>
     *
     * <pre>
     * north side of the grid in web mercator pixels
     * </pre>
     */
    boolean hasNorth();
    /**
     * <code>required int32 north = 3;</code>
     *
     * <pre>
     * north side of the grid in web mercator pixels
     * </pre>
     */
    int getNorth();

    /**
     * <code>required int32 west = 4;</code>
     *
     * <pre>
     * west side of the grid in web mercator pixels
     * </pre>
     */
    boolean hasWest();
    /**
     * <code>required int32 west = 4;</code>
     *
     * <pre>
     * west side of the grid in web mercator pixels
     * </pre>
     */
    int getWest();

    /**
     * <code>required int32 zoom = 5;</code>
     *
     * <pre>
     * zoom level of the grid
     * </pre>
     */
    boolean hasZoom();
    /**
     * <code>required int32 zoom = 5;</code>
     *
     * <pre>
     * zoom level of the grid
     * </pre>
     */
    int getZoom();

    /**
     * <code>required string key = 6;</code>
     *
     * <pre>
     * the key of the field access is measured to
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required string key = 6;</code>
     *
     * <pre>
     * the key of the field access is measured to
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 6;</code>
     *
     * <pre>
     * the key of the field access is measured to
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell> 
        getCellsList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell getCells(int index);
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    int getCellsCount();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    java.util.List<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder> 
        getCellsOrBuilderList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder getCellsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.conveyal.r5.analyst.messages.AccessGrid}
   */
  public static final class AccessGrid extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.conveyal.r5.analyst.messages.AccessGrid)
      AccessGridOrBuilder {
    // Use AccessGrid.newBuilder() to construct.
    private AccessGrid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccessGrid(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AccessGrid defaultInstance;
    public static AccessGrid getDefaultInstance() {
      return defaultInstance;
    }

    public AccessGrid getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AccessGrid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              width_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              height_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              north_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              west_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              zoom_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              key_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                cells_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell>();
                mutable_bitField0_ |= 0x00000040;
              }
              cells_.add(input.readMessage(com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_AccessGrid_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_AccessGrid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.class, com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.Builder.class);
    }

    public static com.google.protobuf.Parser<AccessGrid> PARSER =
        new com.google.protobuf.AbstractParser<AccessGrid>() {
      public AccessGrid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccessGrid(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccessGrid> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <code>required int32 width = 1;</code>
     *
     * <pre>
     * width of the grid
     * </pre>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 width = 1;</code>
     *
     * <pre>
     * width of the grid
     * </pre>
     */
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <code>required int32 height = 2;</code>
     *
     * <pre>
     * height of the grid
     * </pre>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 height = 2;</code>
     *
     * <pre>
     * height of the grid
     * </pre>
     */
    public int getHeight() {
      return height_;
    }

    public static final int NORTH_FIELD_NUMBER = 3;
    private int north_;
    /**
     * <code>required int32 north = 3;</code>
     *
     * <pre>
     * north side of the grid in web mercator pixels
     * </pre>
     */
    public boolean hasNorth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 north = 3;</code>
     *
     * <pre>
     * north side of the grid in web mercator pixels
     * </pre>
     */
    public int getNorth() {
      return north_;
    }

    public static final int WEST_FIELD_NUMBER = 4;
    private int west_;
    /**
     * <code>required int32 west = 4;</code>
     *
     * <pre>
     * west side of the grid in web mercator pixels
     * </pre>
     */
    public boolean hasWest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 west = 4;</code>
     *
     * <pre>
     * west side of the grid in web mercator pixels
     * </pre>
     */
    public int getWest() {
      return west_;
    }

    public static final int ZOOM_FIELD_NUMBER = 5;
    private int zoom_;
    /**
     * <code>required int32 zoom = 5;</code>
     *
     * <pre>
     * zoom level of the grid
     * </pre>
     */
    public boolean hasZoom() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 zoom = 5;</code>
     *
     * <pre>
     * zoom level of the grid
     * </pre>
     */
    public int getZoom() {
      return zoom_;
    }

    public static final int KEY_FIELD_NUMBER = 6;
    private java.lang.Object key_;
    /**
     * <code>required string key = 6;</code>
     *
     * <pre>
     * the key of the field access is measured to
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string key = 6;</code>
     *
     * <pre>
     * the key of the field access is measured to
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 6;</code>
     *
     * <pre>
     * the key of the field access is measured to
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELLS_FIELD_NUMBER = 7;
    private java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell> cells_;
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    public java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell> getCellsList() {
      return cells_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    public java.util.List<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder> 
        getCellsOrBuilderList() {
      return cells_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    public int getCellsCount() {
      return cells_.size();
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell getCells(int index) {
      return cells_.get(index);
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
     *
     * <pre>
     * cells in row-major order
     * </pre>
     */
    public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder getCellsOrBuilder(
        int index) {
      return cells_.get(index);
    }

    private void initFields() {
      width_ = 0;
      height_ = 0;
      north_ = 0;
      west_ = 0;
      zoom_ = 0;
      key_ = "";
      cells_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNorth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZoom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, width_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, height_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, north_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, west_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, zoom_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getKeyBytes());
      }
      for (int i = 0; i < cells_.size(); i++) {
        output.writeMessage(7, cells_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, north_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, west_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, zoom_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getKeyBytes());
      }
      for (int i = 0; i < cells_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, cells_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.conveyal.r5.analyst.messages.AccessGrid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.conveyal.r5.analyst.messages.AccessGrid)
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGridOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_AccessGrid_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_AccessGrid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.class, com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.Builder.class);
      }

      // Construct using com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCellsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        north_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        west_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        zoom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.internal_static_com_conveyal_r5_analyst_messages_AccessGrid_descriptor;
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid getDefaultInstanceForType() {
        return com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.getDefaultInstance();
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid build() {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid buildPartial() {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid result = new com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.north_ = north_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.west_ = west_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.zoom_ = zoom_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.key_ = key_;
        if (cellsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            cells_ = java.util.Collections.unmodifiableList(cells_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.cells_ = cells_;
        } else {
          result.cells_ = cellsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid) {
          return mergeFrom((com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid other) {
        if (other == com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid.getDefaultInstance()) return this;
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasNorth()) {
          setNorth(other.getNorth());
        }
        if (other.hasWest()) {
          setWest(other.getWest());
        }
        if (other.hasZoom()) {
          setZoom(other.getZoom());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000020;
          key_ = other.key_;
          onChanged();
        }
        if (cellsBuilder_ == null) {
          if (!other.cells_.isEmpty()) {
            if (cells_.isEmpty()) {
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureCellsIsMutable();
              cells_.addAll(other.cells_);
            }
            onChanged();
          }
        } else {
          if (!other.cells_.isEmpty()) {
            if (cellsBuilder_.isEmpty()) {
              cellsBuilder_.dispose();
              cellsBuilder_ = null;
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000040);
              cellsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCellsFieldBuilder() : null;
            } else {
              cellsBuilder_.addAllMessages(other.cells_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasNorth()) {
          
          return false;
        }
        if (!hasWest()) {
          
          return false;
        }
        if (!hasZoom()) {
          
          return false;
        }
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.conveyal.r5.analyst.messages.AccessGridOuterClass.AccessGrid) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int width_ ;
      /**
       * <code>required int32 width = 1;</code>
       *
       * <pre>
       * width of the grid
       * </pre>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 width = 1;</code>
       *
       * <pre>
       * width of the grid
       * </pre>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>required int32 width = 1;</code>
       *
       * <pre>
       * width of the grid
       * </pre>
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000001;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 width = 1;</code>
       *
       * <pre>
       * width of the grid
       * </pre>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>required int32 height = 2;</code>
       *
       * <pre>
       * height of the grid
       * </pre>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 height = 2;</code>
       *
       * <pre>
       * height of the grid
       * </pre>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required int32 height = 2;</code>
       *
       * <pre>
       * height of the grid
       * </pre>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000002;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 height = 2;</code>
       *
       * <pre>
       * height of the grid
       * </pre>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        onChanged();
        return this;
      }

      private int north_ ;
      /**
       * <code>required int32 north = 3;</code>
       *
       * <pre>
       * north side of the grid in web mercator pixels
       * </pre>
       */
      public boolean hasNorth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 north = 3;</code>
       *
       * <pre>
       * north side of the grid in web mercator pixels
       * </pre>
       */
      public int getNorth() {
        return north_;
      }
      /**
       * <code>required int32 north = 3;</code>
       *
       * <pre>
       * north side of the grid in web mercator pixels
       * </pre>
       */
      public Builder setNorth(int value) {
        bitField0_ |= 0x00000004;
        north_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 north = 3;</code>
       *
       * <pre>
       * north side of the grid in web mercator pixels
       * </pre>
       */
      public Builder clearNorth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        north_ = 0;
        onChanged();
        return this;
      }

      private int west_ ;
      /**
       * <code>required int32 west = 4;</code>
       *
       * <pre>
       * west side of the grid in web mercator pixels
       * </pre>
       */
      public boolean hasWest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 west = 4;</code>
       *
       * <pre>
       * west side of the grid in web mercator pixels
       * </pre>
       */
      public int getWest() {
        return west_;
      }
      /**
       * <code>required int32 west = 4;</code>
       *
       * <pre>
       * west side of the grid in web mercator pixels
       * </pre>
       */
      public Builder setWest(int value) {
        bitField0_ |= 0x00000008;
        west_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 west = 4;</code>
       *
       * <pre>
       * west side of the grid in web mercator pixels
       * </pre>
       */
      public Builder clearWest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        west_ = 0;
        onChanged();
        return this;
      }

      private int zoom_ ;
      /**
       * <code>required int32 zoom = 5;</code>
       *
       * <pre>
       * zoom level of the grid
       * </pre>
       */
      public boolean hasZoom() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 zoom = 5;</code>
       *
       * <pre>
       * zoom level of the grid
       * </pre>
       */
      public int getZoom() {
        return zoom_;
      }
      /**
       * <code>required int32 zoom = 5;</code>
       *
       * <pre>
       * zoom level of the grid
       * </pre>
       */
      public Builder setZoom(int value) {
        bitField0_ |= 0x00000010;
        zoom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 zoom = 5;</code>
       *
       * <pre>
       * zoom level of the grid
       * </pre>
       */
      public Builder clearZoom() {
        bitField0_ = (bitField0_ & ~0x00000010);
        zoom_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 6;</code>
       *
       * <pre>
       * the key of the field access is measured to
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string key = 6;</code>
       *
       * <pre>
       * the key of the field access is measured to
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 6;</code>
       *
       * <pre>
       * the key of the field access is measured to
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 6;</code>
       *
       * <pre>
       * the key of the field access is measured to
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 6;</code>
       *
       * <pre>
       * the key of the field access is measured to
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 6;</code>
       *
       * <pre>
       * the key of the field access is measured to
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        key_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell> cells_ =
        java.util.Collections.emptyList();
      private void ensureCellsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          cells_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell>(cells_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder> cellsBuilder_;

      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell> getCellsList() {
        if (cellsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cells_);
        } else {
          return cellsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public int getCellsCount() {
        if (cellsBuilder_ == null) {
          return cells_.size();
        } else {
          return cellsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell getCells(int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);
        } else {
          return cellsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder setCells(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.set(index, value);
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder setCells(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.set(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder addCells(com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder addCells(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(index, value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder addCells(
          com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder addCells(
          int index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder addAllCells(
          java.lang.Iterable<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell> values) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cells_);
          onChanged();
        } else {
          cellsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder clearCells() {
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public Builder removeCells(int index) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.remove(index);
          onChanged();
        } else {
          cellsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder getCellsBuilder(
          int index) {
        return getCellsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder getCellsOrBuilder(
          int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);  } else {
          return cellsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public java.util.List<? extends com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder> 
           getCellsOrBuilderList() {
        if (cellsBuilder_ != null) {
          return cellsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cells_);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder addCellsBuilder() {
        return getCellsFieldBuilder().addBuilder(
            com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder addCellsBuilder(
          int index) {
        return getCellsFieldBuilder().addBuilder(
            index, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Cell cells = 7;</code>
       *
       * <pre>
       * cells in row-major order
       * </pre>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder> 
           getCellsBuilderList() {
        return getCellsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder> 
          getCellsFieldBuilder() {
        if (cellsBuilder_ == null) {
          cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell, com.conveyal.r5.analyst.messages.AccessGridOuterClass.Cell.Builder, com.conveyal.r5.analyst.messages.AccessGridOuterClass.CellOrBuilder>(
                  cells_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          cells_ = null;
        }
        return cellsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.conveyal.r5.analyst.messages.AccessGrid)
    }

    static {
      defaultInstance = new AccessGrid(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.conveyal.r5.analyst.messages.AccessGrid)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_conveyal_r5_analyst_messages_CellMinute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_conveyal_r5_analyst_messages_CellMinute_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_conveyal_r5_analyst_messages_Cell_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_conveyal_r5_analyst_messages_Cell_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_conveyal_r5_analyst_messages_AccessGrid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_conveyal_r5_analyst_messages_AccessGrid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/resources/messages/access_gri" +
      "d.proto\022 com.conveyal.r5.analyst.message" +
      "s\"#\n\nCellMinute\022\025\n\raccessibility\030\001 \003(\005\"E" +
      "\n\004Cell\022=\n\007minutes\030\001 \003(\0132,.com.conveyal.r" +
      "5.analyst.messages.CellMinute\"\232\001\n\nAccess" +
      "Grid\022\r\n\005width\030\001 \002(\005\022\016\n\006height\030\002 \002(\005\022\r\n\005n" +
      "orth\030\003 \002(\005\022\014\n\004west\030\004 \002(\005\022\014\n\004zoom\030\005 \002(\005\022\013" +
      "\n\003key\030\006 \002(\t\0225\n\005cells\030\007 \003(\0132&.com.conveya" +
      "l.r5.analyst.messages.Cell"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_conveyal_r5_analyst_messages_CellMinute_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_conveyal_r5_analyst_messages_CellMinute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_conveyal_r5_analyst_messages_CellMinute_descriptor,
        new java.lang.String[] { "Accessibility", });
    internal_static_com_conveyal_r5_analyst_messages_Cell_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_conveyal_r5_analyst_messages_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_conveyal_r5_analyst_messages_Cell_descriptor,
        new java.lang.String[] { "Minutes", });
    internal_static_com_conveyal_r5_analyst_messages_AccessGrid_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_conveyal_r5_analyst_messages_AccessGrid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_conveyal_r5_analyst_messages_AccessGrid_descriptor,
        new java.lang.String[] { "Width", "Height", "North", "West", "Zoom", "Key", "Cells", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
