// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/messages/origin.proto

package com.conveyal.r5.analyst.messages;

public final class OriginOuterClass {
  private OriginOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MinuteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.conveyal.r5.analyst.messages.Minute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * the accessibility distribution at this minute
     * TODO should this be delta coded? Probably not as this is just for moving info between components
     * </pre>
     */
    java.util.List<java.lang.Integer> getAccessibilityList();
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * the accessibility distribution at this minute
     * TODO should this be delta coded? Probably not as this is just for moving info between components
     * </pre>
     */
    int getAccessibilityCount();
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * the accessibility distribution at this minute
     * TODO should this be delta coded? Probably not as this is just for moving info between components
     * </pre>
     */
    int getAccessibility(int index);
  }
  /**
   * Protobuf type {@code com.conveyal.r5.analyst.messages.Minute}
   */
  public static final class Minute extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.conveyal.r5.analyst.messages.Minute)
      MinuteOrBuilder {
    // Use Minute.newBuilder() to construct.
    private Minute(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Minute(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Minute defaultInstance;
    public static Minute getDefaultInstance() {
      return defaultInstance;
    }

    public Minute getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Minute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                accessibility_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              accessibility_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                accessibility_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                accessibility_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          accessibility_ = java.util.Collections.unmodifiableList(accessibility_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Minute_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Minute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.class, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder.class);
    }

    public static com.google.protobuf.Parser<Minute> PARSER =
        new com.google.protobuf.AbstractParser<Minute>() {
      public Minute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Minute(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Minute> getParserForType() {
      return PARSER;
    }

    public static final int ACCESSIBILITY_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> accessibility_;
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * the accessibility distribution at this minute
     * TODO should this be delta coded? Probably not as this is just for moving info between components
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getAccessibilityList() {
      return accessibility_;
    }
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * the accessibility distribution at this minute
     * TODO should this be delta coded? Probably not as this is just for moving info between components
     * </pre>
     */
    public int getAccessibilityCount() {
      return accessibility_.size();
    }
    /**
     * <code>repeated int32 accessibility = 1;</code>
     *
     * <pre>
     * the accessibility distribution at this minute
     * TODO should this be delta coded? Probably not as this is just for moving info between components
     * </pre>
     */
    public int getAccessibility(int index) {
      return accessibility_.get(index);
    }

    private void initFields() {
      accessibility_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < accessibility_.size(); i++) {
        output.writeInt32(1, accessibility_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < accessibility_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(accessibility_.get(i));
        }
        size += dataSize;
        size += 1 * getAccessibilityList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.r5.analyst.messages.OriginOuterClass.Minute prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.conveyal.r5.analyst.messages.Minute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.conveyal.r5.analyst.messages.Minute)
        com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Minute_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Minute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.class, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder.class);
      }

      // Construct using com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accessibility_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Minute_descriptor;
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute getDefaultInstanceForType() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.getDefaultInstance();
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute build() {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Minute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute buildPartial() {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Minute result = new com.conveyal.r5.analyst.messages.OriginOuterClass.Minute(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          accessibility_ = java.util.Collections.unmodifiableList(accessibility_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.accessibility_ = accessibility_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveyal.r5.analyst.messages.OriginOuterClass.Minute) {
          return mergeFrom((com.conveyal.r5.analyst.messages.OriginOuterClass.Minute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveyal.r5.analyst.messages.OriginOuterClass.Minute other) {
        if (other == com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.getDefaultInstance()) return this;
        if (!other.accessibility_.isEmpty()) {
          if (accessibility_.isEmpty()) {
            accessibility_ = other.accessibility_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAccessibilityIsMutable();
            accessibility_.addAll(other.accessibility_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Minute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.conveyal.r5.analyst.messages.OriginOuterClass.Minute) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> accessibility_ = java.util.Collections.emptyList();
      private void ensureAccessibilityIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          accessibility_ = new java.util.ArrayList<java.lang.Integer>(accessibility_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getAccessibilityList() {
        return java.util.Collections.unmodifiableList(accessibility_);
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public int getAccessibilityCount() {
        return accessibility_.size();
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public int getAccessibility(int index) {
        return accessibility_.get(index);
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public Builder setAccessibility(
          int index, int value) {
        ensureAccessibilityIsMutable();
        accessibility_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public Builder addAccessibility(int value) {
        ensureAccessibilityIsMutable();
        accessibility_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public Builder addAllAccessibility(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAccessibilityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accessibility_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 accessibility = 1;</code>
       *
       * <pre>
       * the accessibility distribution at this minute
       * TODO should this be delta coded? Probably not as this is just for moving info between components
       * </pre>
       */
      public Builder clearAccessibility() {
        accessibility_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.conveyal.r5.analyst.messages.Minute)
    }

    static {
      defaultInstance = new Minute(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.conveyal.r5.analyst.messages.Minute)
  }

  public interface AttributeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.conveyal.r5.analyst.messages.Attribute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     *
     * <pre>
     * The key of the grid
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     *
     * <pre>
     * The key of the grid
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     *
     * <pre>
     * The key of the grid
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute> 
        getMinutesList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    com.conveyal.r5.analyst.messages.OriginOuterClass.Minute getMinutes(int index);
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    int getMinutesCount();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    java.util.List<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder> 
        getMinutesOrBuilderList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder getMinutesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.conveyal.r5.analyst.messages.Attribute}
   */
  public static final class Attribute extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.conveyal.r5.analyst.messages.Attribute)
      AttributeOrBuilder {
    // Use Attribute.newBuilder() to construct.
    private Attribute(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Attribute(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Attribute defaultInstance;
    public static Attribute getDefaultInstance() {
      return defaultInstance;
    }

    public Attribute getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Attribute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                minutes_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute>();
                mutable_bitField0_ |= 0x00000002;
              }
              minutes_.add(input.readMessage(com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          minutes_ = java.util.Collections.unmodifiableList(minutes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Attribute_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Attribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.class, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder.class);
    }

    public static com.google.protobuf.Parser<Attribute> PARSER =
        new com.google.protobuf.AbstractParser<Attribute>() {
      public Attribute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Attribute(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Attribute> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     *
     * <pre>
     * The key of the grid
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     *
     * <pre>
     * The key of the grid
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     *
     * <pre>
     * The key of the grid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MINUTES_FIELD_NUMBER = 2;
    private java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute> minutes_;
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    public java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute> getMinutesList() {
      return minutes_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    public java.util.List<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder> 
        getMinutesOrBuilderList() {
      return minutes_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    public int getMinutesCount() {
      return minutes_.size();
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute getMinutes(int index) {
      return minutes_.get(index);
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
     *
     * <pre>
     * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
     * </pre>
     */
    public com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder getMinutesOrBuilder(
        int index) {
      return minutes_.get(index);
    }

    private void initFields() {
      key_ = "";
      minutes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      for (int i = 0; i < minutes_.size(); i++) {
        output.writeMessage(2, minutes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      for (int i = 0; i < minutes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, minutes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.conveyal.r5.analyst.messages.Attribute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.conveyal.r5.analyst.messages.Attribute)
        com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Attribute_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Attribute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.class, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder.class);
      }

      // Construct using com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMinutesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (minutesBuilder_ == null) {
          minutes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          minutesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Attribute_descriptor;
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute getDefaultInstanceForType() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.getDefaultInstance();
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute build() {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute buildPartial() {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute result = new com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (minutesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            minutes_ = java.util.Collections.unmodifiableList(minutes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.minutes_ = minutes_;
        } else {
          result.minutes_ = minutesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute) {
          return mergeFrom((com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute other) {
        if (other == com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (minutesBuilder_ == null) {
          if (!other.minutes_.isEmpty()) {
            if (minutes_.isEmpty()) {
              minutes_ = other.minutes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMinutesIsMutable();
              minutes_.addAll(other.minutes_);
            }
            onChanged();
          }
        } else {
          if (!other.minutes_.isEmpty()) {
            if (minutesBuilder_.isEmpty()) {
              minutesBuilder_.dispose();
              minutesBuilder_ = null;
              minutes_ = other.minutes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              minutesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMinutesFieldBuilder() : null;
            } else {
              minutesBuilder_.addAllMessages(other.minutes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * The key of the grid
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * The key of the grid
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * The key of the grid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * The key of the grid
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * The key of the grid
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       *
       * <pre>
       * The key of the grid
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute> minutes_ =
        java.util.Collections.emptyList();
      private void ensureMinutesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          minutes_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute>(minutes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.OriginOuterClass.Minute, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder, com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder> minutesBuilder_;

      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute> getMinutesList() {
        if (minutesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(minutes_);
        } else {
          return minutesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public int getMinutesCount() {
        if (minutesBuilder_ == null) {
          return minutes_.size();
        } else {
          return minutesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute getMinutes(int index) {
        if (minutesBuilder_ == null) {
          return minutes_.get(index);
        } else {
          return minutesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder setMinutes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute value) {
        if (minutesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinutesIsMutable();
          minutes_.set(index, value);
          onChanged();
        } else {
          minutesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder setMinutes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder builderForValue) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.set(index, builderForValue.build());
          onChanged();
        } else {
          minutesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder addMinutes(com.conveyal.r5.analyst.messages.OriginOuterClass.Minute value) {
        if (minutesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinutesIsMutable();
          minutes_.add(value);
          onChanged();
        } else {
          minutesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder addMinutes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute value) {
        if (minutesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMinutesIsMutable();
          minutes_.add(index, value);
          onChanged();
        } else {
          minutesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder addMinutes(
          com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder builderForValue) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.add(builderForValue.build());
          onChanged();
        } else {
          minutesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder addMinutes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder builderForValue) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.add(index, builderForValue.build());
          onChanged();
        } else {
          minutesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder addAllMinutes(
          java.lang.Iterable<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.Minute> values) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, minutes_);
          onChanged();
        } else {
          minutesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder clearMinutes() {
        if (minutesBuilder_ == null) {
          minutes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          minutesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public Builder removeMinutes(int index) {
        if (minutesBuilder_ == null) {
          ensureMinutesIsMutable();
          minutes_.remove(index);
          onChanged();
        } else {
          minutesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder getMinutesBuilder(
          int index) {
        return getMinutesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder getMinutesOrBuilder(
          int index) {
        if (minutesBuilder_ == null) {
          return minutes_.get(index);  } else {
          return minutesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public java.util.List<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder> 
           getMinutesOrBuilderList() {
        if (minutesBuilder_ != null) {
          return minutesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(minutes_);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder addMinutesBuilder() {
        return getMinutesFieldBuilder().addBuilder(
            com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder addMinutesBuilder(
          int index) {
        return getMinutesFieldBuilder().addBuilder(
            index, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Minute minutes = 2;</code>
       *
       * <pre>
       * The accessibility distribution for each minute; minutes[0] is accessibility at 1 minute and so on.
       * </pre>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder> 
           getMinutesBuilderList() {
        return getMinutesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.OriginOuterClass.Minute, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder, com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder> 
          getMinutesFieldBuilder() {
        if (minutesBuilder_ == null) {
          minutesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveyal.r5.analyst.messages.OriginOuterClass.Minute, com.conveyal.r5.analyst.messages.OriginOuterClass.Minute.Builder, com.conveyal.r5.analyst.messages.OriginOuterClass.MinuteOrBuilder>(
                  minutes_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          minutes_ = null;
        }
        return minutesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.conveyal.r5.analyst.messages.Attribute)
    }

    static {
      defaultInstance = new Attribute(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.conveyal.r5.analyst.messages.Attribute)
  }

  public interface OriginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.conveyal.r5.analyst.messages.Origin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute> 
        getAttributesList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute getAttributes(int index);
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    java.util.List<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder getAttributesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.conveyal.r5.analyst.messages.Origin}
   */
  public static final class Origin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.conveyal.r5.analyst.messages.Origin)
      OriginOrBuilder {
    // Use Origin.newBuilder() to construct.
    private Origin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Origin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Origin defaultInstance;
    public static Origin getDefaultInstance() {
      return defaultInstance;
    }

    public Origin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Origin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                attributes_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute>();
                mutable_bitField0_ |= 0x00000001;
              }
              attributes_.add(input.readMessage(com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Origin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Origin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.class, com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.Builder.class);
    }

    public static com.google.protobuf.Parser<Origin> PARSER =
        new com.google.protobuf.AbstractParser<Origin>() {
      public Origin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Origin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Origin> getParserForType() {
      return PARSER;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 1;
    private java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute> attributes_;
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    public java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    public java.util.List<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
     */
    public com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    private void initFields() {
      attributes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAttributesCount(); i++) {
        if (!getAttributes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(1, attributes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attributes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.conveyal.r5.analyst.messages.OriginOuterClass.Origin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.conveyal.r5.analyst.messages.Origin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.conveyal.r5.analyst.messages.Origin)
        com.conveyal.r5.analyst.messages.OriginOuterClass.OriginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Origin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Origin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.class, com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.Builder.class);
      }

      // Construct using com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.internal_static_com_conveyal_r5_analyst_messages_Origin_descriptor;
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Origin getDefaultInstanceForType() {
        return com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.getDefaultInstance();
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Origin build() {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Origin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.conveyal.r5.analyst.messages.OriginOuterClass.Origin buildPartial() {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Origin result = new com.conveyal.r5.analyst.messages.OriginOuterClass.Origin(this);
        int from_bitField0_ = bitField0_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.conveyal.r5.analyst.messages.OriginOuterClass.Origin) {
          return mergeFrom((com.conveyal.r5.analyst.messages.OriginOuterClass.Origin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.conveyal.r5.analyst.messages.OriginOuterClass.Origin other) {
        if (other == com.conveyal.r5.analyst.messages.OriginOuterClass.Origin.getDefaultInstance()) return this;
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAttributesCount(); i++) {
          if (!getAttributes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.conveyal.r5.analyst.messages.OriginOuterClass.Origin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.conveyal.r5.analyst.messages.OriginOuterClass.Origin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          attributes_ = new java.util.ArrayList<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute>(attributes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder, com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder setAttributes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder setAttributes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(
          com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder addAttributes(
          int index, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public java.util.List<? extends com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.getDefaultInstance());
      }
      /**
       * <code>repeated .com.conveyal.r5.analyst.messages.Attribute attributes = 1;</code>
       */
      public java.util.List<com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder, com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute, com.conveyal.r5.analyst.messages.OriginOuterClass.Attribute.Builder, com.conveyal.r5.analyst.messages.OriginOuterClass.AttributeOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.conveyal.r5.analyst.messages.Origin)
    }

    static {
      defaultInstance = new Origin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.conveyal.r5.analyst.messages.Origin)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_conveyal_r5_analyst_messages_Minute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_conveyal_r5_analyst_messages_Minute_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_conveyal_r5_analyst_messages_Attribute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_conveyal_r5_analyst_messages_Attribute_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_conveyal_r5_analyst_messages_Origin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_conveyal_r5_analyst_messages_Origin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/resources/messages/origin.pro" +
      "to\022 com.conveyal.r5.analyst.messages\"\037\n\006" +
      "Minute\022\025\n\raccessibility\030\001 \003(\005\"S\n\tAttribu" +
      "te\022\013\n\003key\030\001 \002(\t\0229\n\007minutes\030\002 \003(\0132(.com.c" +
      "onveyal.r5.analyst.messages.Minute\"I\n\006Or" +
      "igin\022?\n\nattributes\030\001 \003(\0132+.com.conveyal." +
      "r5.analyst.messages.Attribute"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_conveyal_r5_analyst_messages_Minute_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_conveyal_r5_analyst_messages_Minute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_conveyal_r5_analyst_messages_Minute_descriptor,
        new java.lang.String[] { "Accessibility", });
    internal_static_com_conveyal_r5_analyst_messages_Attribute_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_conveyal_r5_analyst_messages_Attribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_conveyal_r5_analyst_messages_Attribute_descriptor,
        new java.lang.String[] { "Key", "Minutes", });
    internal_static_com_conveyal_r5_analyst_messages_Origin_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_conveyal_r5_analyst_messages_Origin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_conveyal_r5_analyst_messages_Origin_descriptor,
        new java.lang.String[] { "Attributes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
